# Generated by Django 5.1.15 on 2026-05-24 18:02

import django.db.models.deletion
import product.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_file', models.CharField(max_length=512)),
                ('converted_svg', models.CharField(blank=True, max_length=512, null=True)),
                ('mapping_json', models.JSONField(blank=True, null=True)),
                ('preview_image', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('share_token', models.CharField(db_index=True, default=product.models._share_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('completed', 'Completed')], default='active', max_length=50)),
                ('enabled_fields', models.JSONField(blank=True, null=True)),
                ('fonts_config', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='product.template')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('session', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('husband_name', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('roll', models.CharField(blank=True, max_length=50, null=True)),
                ('index_no', models.CharField(blank=True, max_length=50, null=True)),
                ('nid_no', models.CharField(blank=True, max_length=50, null=True)),
                ('joining_date', models.CharField(blank=True, max_length=50, null=True)),
                ('guardians_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_no', models.CharField(blank=True, max_length=50, null=True)),
                ('extra_fields', models.JSONField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('generated_svg', models.CharField(blank=True, max_length=512, null=True)),
                ('generated_pdf', models.CharField(blank=True, max_length=512, null=True)),
                ('generated_eps', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='product.project')),
            ],
        ),
    ]
