# Generated by Django 5.2.6 on 2026-05-25 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_global',
            field=models.BooleanField(default=False, help_text='If true, this template is visible to every subscriber.'),
        ),
        migrations.AddField(
            model_name='template',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a global template (admin-published).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=512)),
                ('is_global', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fonts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_global', 'name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'filename'), name='unique_owner_filename')],
            },
        ),
    ]
