# Generated by Django 5.1.15 on 2026-05-24 09:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Auto-generated if left blank.', max_length=40, unique=True)),
                ('period_start', models.DateField(default=django.utils.timezone.localdate)),
                ('period_end', models.DateField()),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('void', 'Void')], default='unpaid', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, help_text='School / institution / company name (optional).', max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not shown to the subscriber).')),
                ('product_user_email', models.EmailField(blank=True, help_text='Email this subscriber uses to log into the product. Defaults to the email above if left blank.', max_length=254)),
                ('product_user_id', models.IntegerField(blank=True, help_text='Optional: the user id from the product DB, if known.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On hold'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('hold_reason', models.CharField(blank=True, help_text='Why the account is on hold / suspended (shown only to you).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Recurring price per billing cycle.', max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('max_projects', models.PositiveIntegerField(blank=True, help_text='Optional cap on projects. Blank = unlimited.', null=True)),
                ('max_students', models.PositiveIntegerField(blank=True, help_text='Optional cap on students/cards. Blank = unlimited.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive plans can't be assigned to new accounts.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=8)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('paid_on', models.DateField(default=django.utils.timezone.localdate)),
                ('gateway_reference', models.CharField(blank=True, help_text='Transaction id from a payment gateway, if any.', max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='subscribers.invoice')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscribers.subscriber')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscribers.subscriber'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('current_period_start', models.DateField(default=django.utils.timezone.localdate)),
                ('current_period_end', models.DateField(blank=True, help_text='Paid-through date. Auto-filled from the plan cycle if blank.')),
                ('auto_renew', models.BooleanField(default=False, help_text='For manual billing leave this off; a hint for future automation.')),
                ('cancelled_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscribers.subscriber')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscribers.subscriptionplan')),
            ],
            options={
                'ordering': ['-current_period_end'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscribers.subscription'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='subscribers.subscriptionplan'),
        ),
    ]
