# Generated by Django 5.1.15 on 2026-05-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Product project',
                'verbose_name_plural': 'Product projects',
                'db_table': 'projects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('student_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Product student',
                'verbose_name_plural': 'Product students',
                'db_table': 'students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Product user',
                'verbose_name_plural': 'Product users',
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
