# Generated by Django 5.1.15 on 2026-05-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_productproject_productstudent_productuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductProject',
        ),
        migrations.DeleteModel(
            name='ProductStudent',
        ),
        migrations.DeleteModel(
            name='ProductUser',
        ),
    ]
