# Generated by Django 5.2.6 on 2026-05-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_alter_subscriptionplan_billing_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='storage_quota_mb',
            field=models.PositiveIntegerField(default=5000, help_text="Hard cap on this subscriber's storage in megabytes. 0 disables the cap. Admin can raise per-account."),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='storage_used_bytes',
            field=models.BigIntegerField(default=0, help_text="Cached total of the subscriber's on-disk files. Recomputed on every upload and by saas_tick."),
        ),
    ]
